### ISSUE TITLE
Website rebuild

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/handbook#42]
# Objective

* Get the website, docs and handbook into one platform
  * Creates a more consistent feels
  * Stops dead links from appearing
  * It's a better user experience - we can ie link to pages in the docs/handbook from the website
  * It'd be nicer to be blogging in the same structured markdown format as the docs
* With the homepage, we need to make the repo look credible to a developer. They will have questions like:
  * Will this fit what I need?
    * What it does
    * Integrations
    * Does it do mobile and web
  * Is this supported properly?
    * Volume and quality of companies using it
    * GitHub stars
    * Something that shows it has been updated recently
    * Good investors
  * Is this a "tier 1" type project?
    * Does it look buggy / flakey
    * Who built it
  * Is this going to be hard to set up?
    * How do I deploy / are there lots of ways of getting it live into my preferred provider
  * Will this scale? (for some users)
    * Is there an enterprise offering
    * Can I self host
  * Is this cool / will it make me better at my job?
    * Is there a nice looking community around the project
    * Is the design consistent?
    * Are the docs really well written?
  * How is this different to product analytics tool X?
    * I want a big features list
    * Gifs of the product

It's not possible to hit everything above with just the homepage, but this is what I thought we should include to meet as many of these points as possible. This is NOT how the design will look, but is the content and flow:

<img width="1440" alt="posthog-redesign" src="https://user-images.githubusercontent.com/47497682/80494263-62753100-895e-11ea-8188-e79ba5ccff97.png">

* Simple description with some social proof. We can't yet use logos, but we will eventually be able to. This can be a goal in the next few weeks to ask people / create a couple of case studies.
* SaaS and self-managed options made clear. I would have the Free Trial link int he top right take a user to a selection page between hosted / self hosted
* Screenshots of the product (this area needs to be a little stronger design wise) to explain briefly what it does (with links in nav to more detail if needed)
* Designed for your stack to show it's easy to set up
* PostHog for enterprise to show we can support big companies, which means it'll be bug free
* Install now, free - to show it's easy to deploy
* Join the community - to make it seem cool and friendly for developers, since they can interact with us
* What's new - to make it clear it's in active development
* Big footer to demonstrate we're a real company, this isn't a "startup landing page" template

# Review

I'm not after detailed design QA. Any big sections you'd add / remove?

**Comment by EDsCODE** [comment]
Flow is good. I have comments on some of the content and a few things related to design but for pinpointing focus/intent of the page. 

- "Saas/cloud" button: Maybe try copy that directly says "Try hosted for Free." I'm assuming anyone who clicks it will deploy for free first anyway before choosing plan so the free trial in the top right won't need to be there. Will urge even slightly interested to click and give it a shot. Reduce cognitive load needed to go see what the pricing is like.
- I forgot the emphasis we're going for. RE: the action button weights. Are we attempting to drive more hosted usage or self-hosted usage? 
- Social proof: if allowed, we could add some of the major backers? Even YC itself would give pretty strong validation especially in dev community to give it a try
- Changelog can also be an option on the top right menu. 
- "Install now, free": I took a look at mixpanel's analogous banner and I liked their lead in. They ask a question and then give you a call to action/response to your problem. 
- Design related but "Install now, free" options should be made buttons so that they are clickable. The logos might not seem clickable immediately.

**Addition**
- Support/Contact button on the top right as an option. Provide visitors with a direct line of communication.
- Related to previous point, add intercom support? People can rapid fire questions 
- A way to address a bunch of the questions you outlined above is having a really bulletproof FAQ page. We can do this up front or as we learn over the next few weeks/months what people always want to know but given that there's a lot of analytics players in the space, a good FAQ list should do wonders for us.
- Add another section that has 3 key metrics we've hit and would demonstrate high credibility along with the logos we add eventually (maybe later once we have more numbers)

**Comment by jamesefhawkins** [comment]
This is really helpful and gives me a good todo list:

> Flow is good. I have comments on some of the content and a few things related to design but for pinpointing focus/intent of the page.
> 
> * "Saas/cloud" button: Maybe try copy that directly says "Try hosted for Free." I'm assuming anyone who clicks it will deploy for free first anyway before choosing plan so the free trial in the top right won't need to be there. Will urge even slightly interested to click and give it a shot. Reduce cognitive load needed to go see what the pricing is like.

Agreed

> * I forgot the emphasis we're going for. RE: the action button weights. Are we attempting to drive more hosted usage or self-hosted usage?

At the moment at PostHog.com it doesn't make self hosted clear enough. I don't want to eliminate the hosted version completely though since I think many will use it to try us out more easily.

> * Social proof: if allowed, we could add some of the major backers? Even YC itself would give pretty strong validation especially in dev community to give it a try

I thought about this quite hard but drew a different conclusion. I think a ton of startups push their investors. However, better established companies don't do this on their homepages. To me seeing "backed by YC" means "this is potentially going to be flakey". That's why I added it to the footer.

> * Changelog can also be an option on the top right menu.

Changelog should definitely go in there somewhere. I'd argue this is a slightly niche area for existing users so should go into the footer?

> * "Install now, free": I took a look at mixpanel's analogous banner and I liked their lead in. They ask a question and then give you a call to action/response to your problem.

Maybe that's the wrong CTA. I was trying to make the self hos

> * Design related but "Install now, free" options should be made buttons so that they are clickable. The logos might not seem clickable immediately.
> 

This is exactly how I'd want it to work. The logos will need to feel like buttons (https://about.gitlab.com/install/ is a nice example of this)

> **Addition**
> 
> * Support/Contact button on the top right as an option. Provide visitors with a direct line of communication.

Agreed

> * Related to previous point, add intercom support? People can rapid fire questions

Given our demographic, I feel intercom is a bit "salesy", as it pushes its way into your face quite heavily.

> * A way to address a bunch of the questions you outlined above is having a really bulletproof FAQ page. We can do this up front or as we learn over the next few weeks/months what people always want to know but given that there's a lot of analytics players in the space, a good FAQ list should do wonders for us.

Agreed

> * Add another section that has 3 key metrics we've hit and would demonstrate high credibility along with the logos we add eventually (maybe later once we have more numbers)

Agreed

**Comment by EDsCODE** [comment]
> Changelog should definitely go in there somewhere. I'd argue this is a slightly niche area for existing users so should go into the footer?

At this stage, having changelog at the top could help improve trust especially since we're targeting developers. Shows priority in getting the platform built and that's a decent chunk of the praise we've received. I think once we feel we have credibility and achieved relatively big clients that we can show logos of, this can move but for the moment the constant updates are a big selling point

Also, should add docs and about at the top right? This might make the options very cluttered but docs is definitely a link people will look for on our site when they forget. 

Agree with everything else!

**Comment by jamesefhawkins** [comment]
> > Changelog should definitely go in there somewhere. I'd argue this is a slightly niche area for existing users so should go into the footer?
> 
> At this stage, having changelog at the top could help improve trust especially since we're targeting developers. Shows priority in getting the platform built and that's a decent chunk of the praise we've received. I think once we feel we have credibility and achieved relatively big clients that we can show logos of, this can move but for the moment the constant updates are a big selling point
> 

Agreed. Ok let's do that until we are able to have case studies up there. "This looks active" is a big plus for an engineer checking us out + helps with people upgrading to the best version which will help retention... unless it looks super clutere

> Also, should add docs and about at the top right? This might make the options very cluttered but docs is definitely a link people will look for on our site when they forget.
> 
> Agree with everything else!

Agreed.

**Comment by jamesefhawkins** [comment]
This is now superseded by the issues in posthog.com repo
